trigger:
- develop

variables:
  # Nombre de tu ECR y URI (cambia estos valores)
  awsRegion: 'us-east-1'
  ecrRepoName: 'my-ecs-app-develop'
  imageTag: 'latest'

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: Build
  displayName: 'Build and Push Docker Image'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      addToPath: true

  - script: |
      python -m venv venv
      source venv/bin/activate
      pip install -r requirements.txt
    displayName: 'Install dependencies'

  - task: Docker@2
    inputs:
      containerRegistry: 'AWS'
      repository: '$(ecrRepoName)'
      command: 'buildAndPush'
      Dockerfile: 'Dockerfile'
      tags: '$(imageTag)'
    displayName: 'Build and Push Docker Image to ECR'

- job: Deploy
  displayName: 'Deploy to ECS'
  dependsOn: Build
  steps:
  - script: |
      aws ecs update-service --cluster my-ecs-cluster --service myapp-service --force-new-deployment --region $(awsRegion)
    displayName: 'Deploy to ECS'
    env:
      AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
      AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
